books = [
    {
        "id": 1,
        "title": "The Great Gatsby",
        "author": "F. Scott Fitzgerald",
        "publisher": "Scribner",
        "publish_date": "1925-04-10",
        "no_of_pages": 180,
        "language": "English",
        "edition": "1st",
        "price": 10.99,
    },
    {
        "id": 2,
        "title": "To Kill a Mockingbird",
        "author": "Harper Lee",
        "publisher": "J.B. Lippincott & Co.",
        "publish_date": "1960-07-11",
        "no_of_pages": 281,
        "language": "English",
        "edition": "1st",
        "price": 14.99,
    },
    {
        "id": 3,
        "title": "1984",
        "author": "George Orwell",
        "publisher": "Secker & Warburg",
        "publish_date": "1949-06-08",
        "no_of_pages": 328,
        "language": "English",
        "edition": "1st",
        "price": 13.99,
    },
    {
        "id": 4,
        "title": "Pride and Prejudice",
        "author": "Jane Austen",
        "publisher": "T. Egerton",
        "publish_date": "1813-01-28",
        "no_of_pages": 279,
        "language": "English",
        "edition": "1st",
        "price": 9.99,
    },
    {
        "id": 5,
        "title": "The Catcher in the Rye",
        "author": "J.D. Salinger",
        "publisher": "Little, Brown and Company",
        "publish_date": "1951-07-16",
        "no_of_pages": 214,
        "language": "English",
        "edition": "1st",
        "price": 12.99,
    },
    {
        "id": 6,
        "title": "The Hobbit",
        "author": "J.R.R. Tolkien",
        "publisher": "George Allen & Unwin",
        "publish_date": "1937-09-21",
        "no_of_pages": 310,
        "language": "English",
        "edition": "1st",
        "price": 16.99,
    },
    {
        "id": 7,
        "title": "The Lord of the Rings",
        "author": "J.R.R. Tolkien",
        "publisher": "George Allen & Unwin",
        "publish_date": "1954-07-29",
        "no_of_pages": 1178,
        "language": "English",
        "edition": "1st",
        "price": 25.99,
    },
    {
        "id": 8,
        "title": "Moby-Dick",
        "author": "Herman Melville",
        "publisher": "Harper & Brothers",
        "publish_date": "1851-10-18",
        "no_of_pages": 635,
        "language": "English",
        "edition": "1st",
        "price": 11.99,
    },
    {
        "id": 9,
        "title": "Brave New World",
        "author": "Aldous Huxley",
        "publisher": "Chatto & Windus",
        "publish_date": "1932-01-01",
        "no_of_pages": 288,
        "language": "English",
        "edition": "1st",
        "price": 13.50,
    },
    {
        "id": 10,
        "title": "The Alchemist",
        "author": "Paulo Coelho",
        "publisher": "HarperOne",
        "publish_date": "1988-01-01",
        "no_of_pages": 208,
        "language": "English",
        "edition": "1st",
        "price": 12.99,
    },
    {
        "id": 11,
        "title": "The Da Vinci Code",
        "author": "Dan Brown",
        "publisher": "Doubleday",
        "publish_date": "2003-03-18",
        "no_of_pages": 454,
        "language": "English",
        "edition": "1st",
        "price": 17.99,
    },
    {
        "id": 12,
        "title": "Harry Potter and the Sorcerer's Stone",
        "author": "J.K. Rowling",
        "publisher": "Bloomsbury",
        "publish_date": "1997-06-26",
        "no_of_pages": 223,
        "language": "English",
        "edition": "1st",
        "price": 18.99,
    },
    {
        "id": 13,
        "title": "The Hunger Games",
        "author": "Suzanne Collins",
        "publisher": "Scholastic Press",
        "publish_date": "2008-09-14",
        "no_of_pages": 374,
        "language": "English",
        "edition": "1st",
        "price": 14.99,
    },
    {
        "id": 14,
        "title": "The Kite Runner",
        "author": "Khaled Hosseini",
        "publisher": "Riverhead Books",
        "publish_date": "2003-05-29",
        "no_of_pages": 371,
        "language": "English",
        "edition": "1st",
        "price": 15.99,
    },
    {
        "id": 15,
        "title": "A Thousand Splendid Suns",
        "author": "Khaled Hosseini",
        "publisher": "Riverhead Books",
        "publish_date": "2007-05-22",
        "no_of_pages": 372,
        "language": "English",
        "edition": "1st",
        "price": 16.00,
    },
]